name: Terraform Apply 

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform

    env:
        ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
        ARM_TENANT_ID: ${{secrets.TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
            terraform init -backend-config="backend.conf" \
            -upgrade 

      - name: Terraform Apply
        run: |
          terraform apply \
          -auto-approve \
