name: Terraform Destroy 

on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./Terraform
    

    env:
        ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
        ARM_TENANT_ID: ${{secrets.TENANT_ID}}

    steps:
        - uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Terraform Init
          id: init
          run: | 
            terraform init -backend-config="backend.conf" \
            -upgrade 
           
        - name: Terraform Destroy
          run: |
            terraform destroy \
            -auto-approve \

            